/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAdminTasasRouteImport } from './routes/_authenticated/admin.tasas'
import { Route as AuthenticatedAdminCuentasRouteImport } from './routes/_authenticated/admin.cuentas'

const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAdminTasasRoute = AuthenticatedAdminTasasRouteImport.update({
  id: '/admin/tasas',
  path: '/admin/tasas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCuentasRoute =
  AuthenticatedAdminCuentasRouteImport.update({
    id: '/admin/cuentas',
    path: '/admin/cuentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cuentas': typeof CuentasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/tasas': typeof AuthenticatedAdminTasasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cuentas': typeof CuentasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/admin/tasas': typeof AuthenticatedAdminTasasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cuentas': typeof CuentasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/admin/cuentas': typeof AuthenticatedAdminCuentasRoute
  '/_authenticated/admin/tasas': typeof AuthenticatedAdminTasasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cuentas'
    | '/auth/callback'
    | '/admin/cuentas'
    | '/admin/tasas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cuentas'
    | '/auth/callback'
    | '/admin/cuentas'
    | '/admin/tasas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cuentas'
    | '/auth/callback'
    | '/_authenticated/admin/cuentas'
    | '/_authenticated/admin/tasas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CuentasRoute: typeof CuentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/admin/tasas': {
      id: '/_authenticated/admin/tasas'
      path: '/admin/tasas'
      fullPath: '/admin/tasas'
      preLoaderRoute: typeof AuthenticatedAdminTasasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cuentas': {
      id: '/_authenticated/admin/cuentas'
      path: '/admin/cuentas'
      fullPath: '/admin/cuentas'
      preLoaderRoute: typeof AuthenticatedAdminCuentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCuentasRoute: typeof AuthenticatedAdminCuentasRoute
  AuthenticatedAdminTasasRoute: typeof AuthenticatedAdminTasasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCuentasRoute: AuthenticatedAdminCuentasRoute,
  AuthenticatedAdminTasasRoute: AuthenticatedAdminTasasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CuentasRoute: CuentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
